name: Build & Publish Dev Branch as SNAPSHOT
on:
  push:
    branches: [ dev ]

jobs:
  build:
    uses: ./.github/workflows/compile-sources.yml
    with:
      java-version: '17'
      distribution: 'temurin'

  unit-tests:
    needs: build
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      java-version: '17'
      distribution: 'temurin'

  integration-tests:
    needs: build
    uses: ./.github/workflows/run-integration-tests.yml
    with:
      java-version: '17'
      distribution: 'temurin'

  qodana-code-analysis:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.2

  create-and-publish-docker-image:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.4.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean --batch-mode --quiet package spring-boot:repackage -DskipTests
      - name: Publish Docker Container
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: szilex93/round-tracker-be
          tags: snapshot