name: Build & Publish Dev Branch
on:
  push:
    branches: [ dev ]

jobs:
  run-unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      java-version: '17'
      distribution: 'temurin'

  create-and-publish-docker-image:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean --batch-mode --quiet  package -DskipTests
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: szilex93/round-tracker-be
          tags: snapshot