name: On Pull Request Run Tests

on:
  pull_request:
    branches-ignore:
      - 'master'

jobs:
  run-unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      java-version: '17'
      distribution: 'temurin'
  run-integration-tests:
    uses: ./.github/workflows/run-integration-tests.yml
    with:
      java-version: '17'
      distribution: 'temurin'