name: Qodana Code Scan

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  qodana-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}